chore: 코드리팩토링
Project-GM/Shindam pull request #37
Opened 2024-04-01 23:41 UTC by jun9ho

### 관련 이슈

- [#36]

### 세부 사항

- 리팩토링 완료
-
-

### 테스트 결과

- 

### 전달 사항(선택)

-

2024-04-02 02:23 UTC, leejung7308 requested changes
수정할 거 코드에 코멘트 달아놨습니다. 수정 부탁드립니다.

2024-04-02 02:23 UTC, leejung7308 commented on Shindam/Assets/Scripts/Jungho/SceneController.cs
> +    public void LoadingScene(string sceneName, LoadSceneMode mode)
나중에 확장성을 위하여 씬 이름으로 비교하지 말고 리스트로 관리하는 장점을 활용해서 인덱스로 참조할 수 있게 바꿔주시고 모드 어차피 additive로 똑같으니까 모드 빼주세요

2024-04-02 02:23 UTC, leejung7308 commented on Shindam/Assets/Scripts/Jungho/SceneController.cs
> +    public IEnumerator FadeIn(string sceneName, LoadSceneMode mode)
이렇게 페이드인 안에 씬이동을 넣을거면 씬이동 관련 코드는 따로 빼서 씬이동 함수를 만들어서 붙여주세요

2024-04-02 18:16 UTC, jHyuk22 approved these changes
Good

2024-04-03 23:28 UTC, leejung7308 approved these changes
LGTM

2024-04-03 23:31 UTC, merged